### ISSUE TITLE
Relax dependencies with SDL2 and imgui

### ISSUE THREAD

**Issue by rasky** [michaelfairley/rust-imgui-sdl2#13]
`rust-imgui-sdl2` always declares a fixed minor version dependency in `Cargo.toml` for both `imgui` and `sdl2`. For instance, right now on master it is `0.7` and `0.34`. This has always created many problems to me, because I need to coordinate updates of `imgui` and `sdl2` exactly the way `rust-imgui-sdl2` demands. 

For instance, sometimes I would like to upgrade (or even downgrade) sdl2, and I can't do that because `rust-imgui-sdl2` is demanding a fixed version. Basically, my application is forced by `rust-imgui-sdl2` to use specific versions of those libraries, and the only knob I'm left with is the version of `rust-imgui-sdl2` I can declared that I want. This is very limiting: those libraries are much larger than `rust-imgui-sdl2`, there are more developments going on, and it looks wrong that I can't benefit from those until `rust-imgui-sdl2` declares that it's time to do it -- and when it does, maybe it updates both packages creating a different problem to me.

I think `rust-imgui-sdl2` would better serve the community if it was less demanding on the precise versions. In theory, it should allow for maximum compatibility and declare the minimum version of either crate it compiles with, but leaving applications free to handle their own updates. For instance, it could use `sdl2 = ^0.30` and `imgui = ^0.4`, or whatever are the minimum requirements. That would simplify my life a lot.

Thanks!

**Comment by rasky** [comment]
To give you a more specific example, I have an application that requires a fork of `imgui-rs` built upon `v0.2`. On top of that, it needs SDL2 `v0.34` or newer because of bugs in newer macOS with older SDL2 versions.

Now, that combination is perfectly fine. There is no trouble in using `imgui == 0.2` and `sdl2 == 0.34` per-se, but the problem is that there is not a single released version of `rust-imgui-sdl2` that declares that it accepts that combination. The closest is `rust-imgui-sdl2 == 0.7.0`, but that version declares that it wants `imgui == 0.2` and `sdl2 == 0.32.1`, the latter of which doesn't build on newer macOS. So I have to resort to fork `rust-imgui-sdl2`, create a branch off the tag `v0.7.0`, and patch `Cargo.toml` to change `sdl2 == 0.32.1` into `sdl2 == 0.34`, to make my application works.

This seems wrong. The very fact that after the patch, everything works, means that the version declared by `rust-imgui-sdl2` was wrong; v0.7.0 didn't really require *specifically* `0.32.1`, since it does work with `0.34`, and possibly with many many other versions of `sdl2`; this notwithstanding, it is declaring a fixed dependency with exactly `sdl2 == 0.32.1`, like that it is the only version that it can work with.

**Comment by michaelfairley** [comment]
Thanks for pointing this out! I've relaxed the version dependencies a bit and will generally keep them as relaxed as possible going forward.
