### ISSUE TITLE
Why is the crate limited to a certain sdl version?

### ISSUE THREAD

**Issue by iddm** [michaelfairley/rust-imgui-sdl2#18]
https://github.com/michaelfairley/rust-imgui-sdl2/blob/ffca07d9721f64b5082e4fd4dd42382a9ba30750/Cargo.toml#L14C1-L14C23

Because of this it is impossible to use the sdl2 crate with the recent changes which I need. Note that 0.36 has never been published (yet), and 0.35 is very old (two years), so it makes sense to remove this limitation, since many people want to actually use both, sdl2 crate and this one.

**Comment by michaelfairley** [comment]
Most new minor versions of the sdl2 crate have backwards incompatible changes that don't work with the existing version of this crate, so this prevents the incompatible versions from trying to work together. If a new version of the sdl2 crate does work with the existing version of this crate, it's a 1 character change to get them working together happily.

Given that there's not an rust-sdl2 0.36 yet, what incompatibility are you running into?

**Comment by iddm** [comment]
Hi there! Now there is a sdl2 (0.36) and imgui-sdl2 is limiting in a way that I can't build the crates anymore that depend on it. Will you change this crate in order to make them compatible or you weren't planning to do that?

**Comment by michaelfairley** [comment]
Done in 0.15.3

**Comment by iddm** [comment]
Thanks!
