### ISSUE TITLE
show_demo_window doing nothing?

### ISSUE THREAD

**Issue by Wowo10** [michaelfairley/rust-imgui-sdl2#3]
Hello!
I have downloaded you repo and tried the example demo app.
It shows empty window, but looking at the code there is 
`ui.show_demo_window(&mut true);`
So I assume there should be visible default demo imgui window
![image](https://user-images.githubusercontent.com/18621537/47648967-fc96c600-db7b-11e8-81c7-8678d6abd8a5.png)
But it is not. What should it display actually?

**Comment by michaelfairley** [comment]
It should display that imgui demo window 😕.

Do you happen to be using MacOS Mojave?

**Comment by Wowo10** [comment]
Nah, I am running at Xubuntu 18.04 lts

**Comment by Wowo10** [comment]
Okay I have compiled it on other PC (Windows OS) and I can see the demo window.
I will note resolution steps on Xubuntu when I will find them.
Cheers!

**Comment by jupart** [comment]
Does not show on Arch Linux either, I've checked to make sure the sdl2 libs are all installed.

**Comment by jupart** [comment]
OK, changing `gl_attr.set_context_version(3, 0);` to 3.1 or something makes it work!

**Comment by michaelfairley** [comment]
Thanks for figuring that out! I'm pretty sure the example is only using OpenGL 3.0 features, but I'll go over it in more detail to make sure that's completely accurate. If it does indeed require 3.1, I'll either change the code so it doesn't or bump that version requirement.

FWIW, the demo does work on my Arch Linux system, so I'm guessing the source of this issue is in some graphics card drivers. Which graphics cards are y'all using in your Linux boxes that are getting the black screens?

**Comment by Wowo10** [comment]
Changing to 3.1 seems work for me <3.
Card I am using is Intel HD 4000 inside my Lenovo X230.

**Comment by jupart** [comment]
Here's the relevant bits of my `glxinfo`

```
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile
OpenGL core profile version string: 4.2 (Core Profile) Mesa 18.2.2
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.2.2
```

**Comment by michaelfairley** [comment]
Hi! I just pushed a new version of [rust-imgui-opengl-renderer](https://github.com/michaelfairley/rust-imgui-opengl-renderer) that I hope will fix this problem, but I unfortunately don't have a Linux+Intel machine to test one. Could one of you try running this example again, making sure your imgui-opengl-renderer dependency is at 0.3.2 and let me know if it works?

**Comment by jupart** [comment]
It seems to work without issue. Thanks!
